tap "aws/tap"
tap "borkdude/brew"
tap "clojure/tools"
tap "coursier/formulas"
tap "d12frosted/emacs-plus"
tap "golangci/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "reveel-it/hacks", "git@github.com:reveel-it/homebrew-hacks.git"
brew "awscli"
brew "bash"
brew "bash-completion@2"
brew "ccache"
brew "cmake"
brew "coreutils"
brew "direnv"
brew "fd"
brew "libtool"
brew "gnutls"
brew "harfbuzz"
brew "ffmpeg"
brew "ghostscript"
brew "git"
brew "go"
brew "graphviz"
brew "grip"
brew "imagemagick"
brew "jq"
brew "libvterm"
brew "magic-wormhole"
brew "markdown"
brew "mas"
brew "mupdf-tools"
brew "mysql-client"
brew "neofetch"
brew "ninja"
brew "pandoc"
brew "parquet-tools"
brew "platformio"
brew "postgresql", restart_service: true
brew "qpdf"
brew "rabbitmq", restart_service: true
brew "ripgrep"
brew "rlwrap"
brew "rust-analyzer"
brew "shellcheck"
brew "starship"
brew "trash"
brew "watchman"
brew "xpdf"
brew "yarn"
brew "aws/tap/aws-sam-cli"
brew "borkdude/brew/clj-kondo"
brew "clojure/tools/clojure"
brew "coursier/formulas/coursier"
brew "d12frosted/emacs-plus/emacs-plus@27", args: ["with-modern-alecive-flatwoken-icon"]
brew "golangci/tap/golangci-lint"
brew "heroku/brew/heroku"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai", args: ["HEAD"]
cask "amethyst"
cask "discord"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "gpg-suite-no-mail"
cask "iterm2"
cask "karabiner-elements"
cask "keka"
cask "michaelvillar-timer"
cask "ngrok"
cask "nosql-workbench"
cask "signal"
cask "temurin"
cask "ubersicht"
cask "visual-studio-code"
mas "1Password 7", id: 1333542190
mas "Keynote", id: 409183694
mas "Microsoft Excel", id: 462058435
mas "Microsoft OneNote", id: 784801555
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
