# this is because Prettier formats package.json files differently than any other json file 🤦
# to get this to work, symlink runtime/queries/json to runtime/queries/package.json
# Thank you https://github.com/helix-editor/helix/issues/3596#issuecomment-1853407163
[[language]]
name = "package.json"
scope = "source.json"
roots = ["package.json"]
file-types = [{ glob = "package.json" }, { glob = "package-lock.json" }, { glob = "composer.json" }]
formatter = { command = "npx", args = ["--", "prettier", "--stdin-filepath", "%{buffer_name}"] }
# language-servers = ["vscode-json-language-server"]
auto-format = true
grammar = "json"

[[language]]
name = "markdown"
formatter = { command = "npx", args = ["--", "prettier", "--stdin-filepath", "%{buffer_name}"] }
auto-format = true

[[language]]
name = "html"
formatter = { command = "npx", args = ["--", "prettier", "--stdin-filepath", "%{buffer_name}"] }

[[language]]
name = "json"
formatter = { command = "npx", args = ["--", "prettier", "--stdin-filepath", "%{buffer_name}"] }
auto-format = true

[[language]]
name = "jsonc"
formatter = { command = "npx", args = ["--", "prettier", "--stdin-filepath", "%{buffer_name}"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = "npx", args = ["--", "prettier", "--stdin-filepath", "%{buffer_name}"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = ["typescript-language-server", "vscode-eslint-language-server"]
formatter = { command = "npx", args = ["--", "prettier", "--stdin-filepath", "%{buffer_name}"] }
auto-format = true

[[language]]
name = "typescript"
language-servers = ["typescript-language-server", "vscode-eslint-language-server"]
formatter = { command = "npx", args = ["--", "prettier", "--stdin-filepath", "%{buffer_name}"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = ["typescript-language-server", "vscode-eslint-language-server"]
formatter = { command = "npx", args = ["--", "prettier", "--stdin-filepath", "%{buffer_name}"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = ["typescript-language-server", "vscode-eslint-language-server"]
formatter = { command = "npx", args = ["--", "prettier", "--stdin-filepath", "%{buffer_name}"] }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = "npx", args = ["--", "prettier", "--stdin-filepath", "%{buffer_name}"] }
auto-format = true

[[language]]
name = "python"
language-servers = ["basedpyright", "ruff"]
formatter = { command = "sh", args = ["-c", "ruff format - | ruff check --select I --fix -"] }
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "clojure"
formatter = { command = "cljfmt", args = ["fix", "-"] }
auto-format = true

[[language]]
name = "cpp"
auto-format = true
